workos/authkit-js

src/index.ts
src/utils/session-data.ts

(also adding the new-ish `permissions` claim)

Export `getClaims`

---

src/create-client.ts
src/index.ts
src/interfaces/create-client-options.interface.ts
src/utils/session-data.ts

This is useful for apps that want to react to changes to the user/access token.

Add `onRefresh` callback

---

src/create-client.ts

The name `onRefresh` is suddenly less accurate, but you definitely want this logic to run on all authentication responses.

call `onRefresh` after code is exchanged

---

src/create-client.ts

We intend to refresh _before_ tokens expire, but previously this code was very unfortunately refreshing shortly after tokens expire.

fix refresh timing

---

src/create-client.ts
src/errors.ts
src/index.ts
src/utils/authenticate-with-refresh-token.ts

(Previously this could return undefined).

always throw when `getAccessToken` fails

---

src/create-client.ts
src/interfaces/create-client-options.interface.ts

This callback fires when a session refresh failed (sessions ended, session was revoked, user was deleted, etc.)

add `onRefreshError`

---

src/create-client.ts

authkit-js attempts to refresh the session when the page loads (unless a code is present). This initial request should NOT trigger the `onRefreshFailure` logic.

don't trigger onRefreshFailure on initial refresh

---

src/create-client.ts

previously `needsRefresh` was returning false when in states "ERROR" / "INITIAL", but that is incorrect.

improve `_needsRefresh` logic

---

src/create-client.ts

`getAccessToken` will still refresh when necessary, but there's no reason to eagerly fetch refresh tokens when `document.hidden`. (This also avoids making unnecessary requests and lowers the risk of being unable to acquire the tab lock).

don't proactively refresh on hidden tabs

---

src/create-client.ts

This is not useful information since the initial refresh is expected to fail for any first time visitors, expired sessions, etc.

stop console.error initial refresh

---

src/create-client.ts

`refreshSession` shouldn't be called directly. Developers should call `getAccessToken` which refreshes the session as needed.
Removed the authkitClientState checks from `refreshSession` (this avoids issues like `getAccessToken` not refreshing when a concurrent refresh has already started. (More improvements to come for avoiding needless refreshes).

make `refreshSession` private

---

src/create-client.ts
src/interfaces/get-authorization-url-options.interface.ts
src/utils/get-authorization-url.ts

When implementing the "Initiate Login" endpoint, the `context` search param should be passed to `signIn`.

support the new `context` parameter in signIn/signUp

---

src/create-client.ts

explain how the code verifier can be missing in console error

---

src/create-client.ts
src/interfaces/create-client-options.interface.ts

Adds a new `refreshBufferInterval` representing how long before the current access token expires to start attempting to refresh. For apps that may run in poor network conditions, this gives their clients more of a buffer.

Add option to configure refresh buffer interval

---

jest.setup.ts
package.json
src/create-client.ts
src/testing/mock-web-locks.ts
src/utils/locking.test.ts
src/utils/locking.ts

The [Web Locks API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API) should be more robust, so we should prefer it when it is available.
[Browser support is currently at 93%](https://caniuse.com/mdn-api_navigator_locks) so we'll likely _only_ support this locking mechanism in the future, but for now will fall back to the current "userspace" library to not change the browsers supported by the SDK.

Use native Web Locks API when available

---

src/create-client.ts

This class fulfills the same interface that the previous anonymous object returned by `createClient` did, so these should not be a breaking change.
In the future, we may want to consider removing `createClient` completely and have callers instantiate `Client` directly (or maybe call a factory/`static` method like `Client.initialize`).

Convert `createClient` internals to a `class`

---

src/create-client.test.ts
src/create-client.ts

Fixes #52.
Refresh errors are expected to happen (session ends, user is not logged in yet, etc.). This is sometimes useful information when debugging, so we should use `console.debug` instead of `console.error`.

stop `console.error`ing on expected errors

---

src/create-client.test.ts
src/create-client.ts
src/errors.ts
src/utils/authenticate-with-code.ts

It was previously possible for multiple outbound /user_management/authenticate requests to happen simultaneously if `getAccessToken` was called multiple times when the current access token had expired.
This PR moves the authenticate request into the client state so that subsequent calls to `getAccessToken` can just await the existing one.

piggy-back on current authentication request

---

src/create-client.test.ts
src/create-client.ts
src/interfaces/authentication-response.interface.ts
src/interfaces/create-client-options.interface.ts

The SDK owns the refresh token. There is no useful reason to expose it to the application.

omit refreshToken from `onRefresh`

---

src/create-client.test.ts
src/create-client.ts

We now set a javascript-accessible `workos-has-session` cookie when the user is logged in. We don't need to attempt to refresh if that cookie is not present.

only attempt initial refresh when likely to succeed

---

src/create-client.test.ts
src/create-client.ts

The ERROR state is meant to indicate terminal errors (like the session being over). authkit-js will not attempt to retrieve new tokens after when in an ERROR state.
Temporary errors (like `fetch` or tab-lock errors) should _not_ move to the error state. This allows future calls to `getAccessToken` to attempt to retrieve a new token.

don't transition to error state for fetch/etc. errors

---

src/create-client.test.ts
src/create-client.ts

This fixes a regression when running in devMode. The session wasn't automatically attempting to refresh on page load as it should.

fix initial refresh in dev mode

---

src/create-client.ts

https://github.com/workos/authkit-js/issues/77
1. Fixed the issue where the method wasn't being called
2. Changed `.then` to `.finally` so Refreshes will carry on if a Error occurs

fix: subsequent refreshes

---

src/create-client.ts

authkit-js [supports impersonation](https://github.com/workos/authkit-js/pull/69). This PR removes an error message indicating it doesn't.

Remove 'impersonation coming soon' error message

---

src/create-client.test.ts
src/create-client.ts

This pull request introduces a new feature to allow forced refresh of access tokens in the `Client` class and adds corresponding test coverage. The most important changes include updating the `getAccessToken` method to support a `forceRefresh` option and adding a test case to verify this behavior.
* [`src/create-client.ts`](diffhunk://#diff-781608bae5ee50dc3205452ef8edee06506f484c4cdab631c0494c7abb6771beL143-R144): Updated the `getAccessToken` method in the `Client` class to accept an optional `forceRefresh` parameter. When `forceRefresh` is true, the access token is refreshed regardless of its expiration status.
* [`src/create-client.test.ts`](diffhunk://#diff-0e70951cb32ea9343aa70d26ce568a18783c6bf923d5dcfd2b3a240ac3bc0e42R525-R556): Added a new test case to ensure the `getAccessToken` …

Add forceRefresh option to `getAccessToken` method

---

src/create-client.test.ts
src/create-client.ts
src/utils/is-redirect-callback.test.ts
src/utils/is-redirect-callback.ts

- **Problem 1**: `signIn()`, `signUp()`, and default `signOut()` broke in WebViews by opening URLs in the external browser.
**Solution 1**: Added `getSignInUrl()`, `getSignUpUrl()` to get URLs without auto-redirect and a `noRedirect` option for `signOut()`.
- **Problem 2**: `isRedirectCallback()` failed in WebViews due to different URL schemes.
**Solution 2**: Now `isRedirectCallback()` only compares the URL path, ignoring the scheme.
- **Impact**: authkit-js is now compatible with hybrid mobile apps without breaking navigation. Tests added and an existing test fixed.
This pull request introduces two key fixes to enable authkit-js to work properly in mobile app WebViews (Android and iOS):
1. **The use of window.location.assign() breaks the mobile app authentication flow** 
-> Added new …

Improve compatibility with hybrid mobile apps

---

src/interfaces/jwt.interface.ts

Add `feature_flags` claim on jwt interface. This change will be used in `authkit-react` to add support for the `feature_flags` JWT claim in https://github.com/workos/authkit-react/pull/65

Add `feature_flags` claim on jwt interface
